//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottishGlen
{
    using System;
    using System.Collections.Generic;
    
    public partial class scottishGlen
    {
        public int ID { get; set; }
        public string systemName { get; set; }
        public string model { get; set; }
        public string manufacturer { get; set; }
        public string type { get; set; }
        public string ipAdress { get; set; }
        public byte[] phySticker { get; set; }
        public string notes { get; set; }
    }
}
