//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScottishGlen
{
    using System;
    using System.Collections.Generic;
    
    public partial class softrec
    {
        public int ID { get; set; }
        public string sysName { get; set; }
        public string sysVersion { get; set; }
        public string sysManufacturer { get; set; }
        public Nullable<int> hardwareID { get; set; }
    }
}
